# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grades_pb2 as grades__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grades_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GradeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGradesAverage = channel.unary_unary(
                '/grades.GradeService/GetGradesAverage',
                request_serializer=grades__pb2.Empty.SerializeToString,
                response_deserializer=grades__pb2.GradeAverageResponse.FromString,
                _registered_method=True)


class GradeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGradesAverage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GradeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGradesAverage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGradesAverage,
                    request_deserializer=grades__pb2.Empty.FromString,
                    response_serializer=grades__pb2.GradeAverageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grades.GradeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grades.GradeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GradeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGradesAverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grades.GradeService/GetGradesAverage',
            grades__pb2.Empty.SerializeToString,
            grades__pb2.GradeAverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
